# This workflow check whether the project passes TypeScript's type checker

name: Check the types of the project using tsc

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]
    
  workflow_dispatch:

jobs:
  # Job to check the types
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Install TypeScript
        run: npm i -g typescript

      - name: Check the types 
        run: tsc --noEmit
